language: generic

script:
  - echo "this should succeed"; true
  - echo "this should fail"; false
  - touch myfile; echo "this shouldn't be executed"; true

after_success:
  - echo "after_success shouldn't be executed"; true

after_script:
  - test -f myfile && echo "this sucks"; true

deploy:
  provider: script
  script: echo "deploy shouldn't be executed; true"
